### ISSUE TITLE
Event listeners have the same time

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv-ui#221]
### Problem description

I don't know if that is a frontend or backend problem. But the time for listening events is always the same for all events. The last event updates them all.

![listener1](https://user-images.githubusercontent.com/10879611/150467986-df5e6d66-7eef-4987-b0f8-65124f1b531b.png)

![listenr2](https://user-images.githubusercontent.com/10879611/150467997-de38322f-4102-4b47-9c28-cc6212436661.png)

**Comment by alankm** [comment]
This appears to be a database issue. Pinpointing the exact cause may take time, because this field is auto-managed by the database, not us.
