### ISSUE TITLE
Make Revision does not save first

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv-ui#225]
### Problem description

If a user changes the workflow and presses "Make Revision" the workflow is not getting saved first.

**Comment by jamesjmurtagh** [comment]
The solution here would be to either emulate the 'Run' button (which becomes unclickable until changes are saved) or to simply add the "Save" functionality to the "Make Revision" function call. Which would you prefer?

**Comment by jensg-st** [comment]
Like run. Only possible if it had been saved. Probably easier too.
