### ISSUE TITLE
Settings: Deleting secrets does not work

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv-ui#228]
### Problem description

Deleting a secret shows the following error but the secret is getting deleted.

![secret1](https://user-images.githubusercontent.com/10879611/150626403-37efa52f-2d81-4c7a-9d61-b3ff52148715.png)

**Comment by jamesjmurtagh** [comment]
I suspect this is because the logic that handles the API is calling `.json()` on the response object, when the response does not contain valid JSON.

**Comment by jensg-st** [comment]
But that had been tested before. That's why I was I'm surprised.

**Comment by porleaaron** [comment]
yes @jamesjmurtagh , there is an exception in react-direktive-hooks to sendback the response to UI

**Comment by porleaaron** [comment]
Actually the api is invoked and the response is 200 and secrete is deleted on server
But hook is trying to return response.json() which is throwing exception

**Comment by jamesjmurtagh** [comment]
@jalfvort Are you able to update this react hook to resolve the issue?
It looks like it's the same issue as the Namespace one that you resolved yesterday.
