### ISSUE TITLE
Global Registries don't have "Test Connection"

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv-ui#230]
### Summary

Namespace services have a "Test Connection" button, both global ones don't.

![registries1](https://user-images.githubusercontent.com/10879611/150660092-bf2c5fe2-db7e-4e16-b1f4-3579cb2c95b3.png)

**Comment by jamesjmurtagh** [comment]
In trying to add this functionality to the 'global' registries panels, I've noticed that the `Test Connection` button doesn't work at all. You can feed it nonsense (ie. `httpz://docker.io`) and it will respond with `Connection seems good!`)
