### ISSUE TITLE
Secret list is not aligned

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv-ui#261]
### Summary

Secrets with different length makes the secret list unaligned. It looks a bit messy. Additionally we should probably shorten long secret names to something like ```my-long-s...123``` if the exceed a certain threshold.

![secrets aligned](https://user-images.githubusercontent.com/10879611/151454030-b6a2241b-388a-4bba-9520-d143fedf316d.png)

**Comment by jalfvort** [comment]
https://github.com/direktiv/direktiv-ui/commit/96fe35fbe7807f8369329a12cf8c96a8372e0bc9
