### ISSUE TITLE
Registry Test Connection does not clear previous result

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv-ui#276]
### Summary

The UI is not cleaning the first error if the second login attempt is successful. 

![registries](https://user-images.githubusercontent.com/10879611/153522416-ae928020-50e1-4390-8771-5cf9c1c00f6c.png)

**Comment by jalfvort** [comment]
https://github.com/direktiv/direktiv-ui/commit/ceb86a233da667bd31ca3f79d4bbce126ec4ee46
