### ISSUE TITLE
Workflow Settings: Warning is not aligned for too large variables

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv-ui#282]
### Summary

The warning message is left aligned and look a bit weird.

![size](https://user-images.githubusercontent.com/10879611/155279322-9dadd155-dffd-43a9-a7b0-5eeb8c7e47fe.png)

**Comment by jalfvort** [comment]
https://github.com/direktiv/direktiv-ui/commit/14cf2259d3809b7709b9ab4886fb90831ef48d3e
